server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.200.3:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'